services:
  - type: web
    name: streamlit-doc-chat
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.enableCORS=false
    envVars:
      - key: GOOGLE_API_KEY
        value: "AIzaSyDaEuO97ZMQAw5du3HvsXLE8vQQyH6yZBg"  # hoặc để trống nếu cấu hình qua trang web Render

